### ISSUE TITLE
Omniglot train / test

### ISSUE THREAD

**Issue by semin-park** [amzn/metalearn-leap#2]
https://github.com/amzn/metalearn-leap/blob/1436ee3029bf5de7cd8e317b9bbf56ff02f46a6c/src/omniglot/data.py#L232-L247

I believe `if self.train:` (L244) should be `if self._train`. What do you think? Since `if self.train` is defined as a function, it'll always be evaluated to `True`, so calling `.eval()` would be pointless.

**Comment by flennerhag** [comment]
I think you're right : ) Thanks for pinging us!
