### ISSUE TITLE
SubOmniglot dataset

### ISSUE THREAD

**Issue by semin-park** [amzn/metalearn-leap#4]
In `DataContainer.__init__`, there are `self.data_train, self.data_test, self.data_val` defined. Each of the `self.data_*` is a list of `SubOmniglot` in which it also defines methods such as `.train(), .eval()`. However, I do not understand why `SubOmniglot` requires such methods. Are they ever used?

If I understood correctly, `DataContainer` handles which `SubOmniglot` datasets are going to be used as train / test / val tasks. Could a `SubOmniglot` be a part of `data_train` but at the same time satisfy `self._train == False`?

https://github.com/amzn/metalearn-leap/blob/1436ee3029bf5de7cd8e317b9bbf56ff02f46a6c/src/omniglot/data.py#L232-L247

**Comment by flennerhag** [comment]
`DataContainer` manages things on a task level (train, val, and test tasks),  `SubOmniglot` handles things on a data-point level.

More specifically, each task is a `SubOmniglot` instance, and each task has a `train` and `eval` set. For each task, we adapt task-learners on the task's `train` set and evaluate the adapted learner on the task's `eval` set: see [here](https://github.com/amzn/metalearn-leap/blob/master/src/omniglot/wrapper.py#L64).

Consequently, a train task (a`SubOmniglot` instance) has both a `train` and `eval` data set, and likewise for val and test tasks.

**Comment by semin-park** [comment]
Oh I see! Thanks for the clear explanation :)

Closing this one 👍
